### ISSUE TITLE
list_vesting_delegations is missing from Radiator::DatabaseApi

### ISSUE THREAD

**Issue by krischik** [inertia186/radiator#27]
Just noted that list_vesting_delegations is missing from the Radiator::DatabaseApi:

```
/opt/local/lib/ruby2.6/gems/2.6.0/gems/radiator-0.4.4/lib/radiator/api.rb:365:in `method_missing': undefined method `list_vesting_delegations' for #<Radiator::DatabaseApi:0x00007fccda075608> (NoMethodError)
```
It is included in steem-ruby.

**Comment by inertia186** [comment]
Use `condenser_api.get_vesting_delegations` instead.  Although Steemit, Inc. has said that `condenser_api` will one day be deprecated, there does not appear to be any plans to actually deprecate it anytime soon.

In fact, they're still actively supporting `condenser_api` with HF21 SPS.  My eventual plan is to try to integrate `steem-ruby` so that it provides methods to `radiator`.
